server:
  port: 8089

api:
  url:
    domain: "jsonplaceholder.typicode.com"
    endpoint: 
      users: "/users"
      posts: "/posts"

spring:
  datasource:
    # driverClassName: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5432/bootcamp"
    username: postgres
    password: admin1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      # create-drop,update,create,none
      # driverClassName: "com.mysql.jdbc.Driver"
      # url: "jdbc:mysql://localhost:3306/bc2405p_db"
      # dialect: "org.hibernate.dialect.MySQL8Dialect"