FROM openjdk:17
LABEL maintainer="itsupport@gmail.com"
ADD target/demo-sb-helloworld-1.0.0-SNAPSHOT.jar demo-sb-helloworld-1.0.0-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar","demo-sb-helloworld-1.0.0-SNAPSHOT.jar"]
EXPOSE 8090