server:
  port: 8081

api:
  url:
    domain: "jsonplaceholder.typicode.com"
    endpoint: "/users"

spring:
  datasource:
    # driverClassName: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5432/bc2405p_db"
    username: postgres
    password: admin1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update # create-drop,update,
      # driverClassName: "com.mysql.jdbc.Driver"
      # url: "jdbc:mysql://localhost:3306/bc2405p_db"
      # dialect: "org.hibernate.dialect.MySQL8Dialect"